const myPromise = () => {
  return new Promise((resolve, reject) => {
    try {
      console.log("Test myPromise OK");
      resolve(console.log("ðŸŸ¢ SUCCESS : my resolve"));
    } catch (error) {
      console.log("ðŸŸ  TRY CATCH ERROR : my error :", error);
      reject(console.log("ðŸŸ  TRY CATCH ERROR : my reject :", error));
    }
  });
};
